### ISSUE TITLE
MacOS version

### ISSUE THREAD

**Issue by amadeous** [anaseto/boohu#17]
I wanted to play but there is no MacOS version. I had to compile for MacOS 10.11.6. It does work on my machine.
If other MacOS users want to play, they have either to compile the sources or they could try with the executable in the zip below.
[boohu.zip](https://github.com/anaseto/boohu/files/2025810/boohu.zip)

**Comment by anaseto** [comment]
Good to know it works well on MacOS. I'll provide MacOS binaries too for the next release, then.

Thanks for testing!

**Comment by amadeous** [comment]
Cool thanks ! :D

**Comment by anaseto** [comment]
So, I put [MacOS binaries](https://github.com/anaseto/boohu/releases/download/v0.8.0/boohu-0.8-darwin_amd64.tar.gz) for the 0.8 release (darwin 64-bit). I'll be glad if you can confirm they work, thanks!

**Comment by amadeous** [comment]
They work for me :)
Thanks !

**Comment by anaseto** [comment]
Thanks for testing. Closing the issue, then :)
