### ISSUE TITLE
Kpad not working unless NumLock is on

### ISSUE THREAD

**Issue by kilobyte** [anaseto/boohu#18]
The arrow keys don't work unless NumLock is in the wrong state.  I understand that some *heretics* insist on having it on, but most people have pretty strong opinion about this (wanting it to stay the hell on or the hell off).  It's pretty annoying to suddenly have arrows broken after playing this game or when temporarily switching away from it.

Thus, could you please recognize arrow key codes as well?

**Comment by anaseto** [comment]
I'll give a look into that, thanks.

**Comment by anaseto** [comment]
Done!
