### ISSUE TITLE
Colours are messed up

### ISSUE THREAD

**Issue by VedVid** [anaseto/boohu#25]
I'm playing standalone ASCII version on Windows 10. Release 0.10 worked well, but playing 0.11 is nearly impossible due to colour scheme. Walls are "covered" by FOV layer:  
![image](https://user-images.githubusercontent.com/16949680/49298376-801a3e80-f4bd-11e8-8d23-106ae9c42d57.png)

Solarized palette is not good either, because it's  eye-tiring:  
![image](https://user-images.githubusercontent.com/16949680/49298409-a17b2a80-f4bd-11e8-81b6-e8aa201e3a1a.png)

On screenshots I'm using cmder terminal emulator, but on default windows command line effect is the same.

Screenshot of Boohu 0.10:  
![image](https://user-images.githubusercontent.com/16949680/49298616-30884280-f4be-11e8-9144-d3197da6214a.png)

**Comment by anaseto** [comment]
Does the problem persist if you toggle twice again the dark/light setting with `=` and then `b`? (just to be sure it's not because of some incompatibility of config between versions) I may have screwed something up, some of the drawing code was factorized during development of the last version. I'll have a look into it.

**Comment by VedVid** [comment]
It helped - after toglling dark/light settings, walls are displayed correctly even in default mode. 

edit: I'm using different versions of Boohu in separate folder, so local config files should not overlap.

**Comment by anaseto** [comment]
There was indeed a bug when no config file was present (it did kind of a mix of the two dark/light themes). The above commit should fix the issue.

**Comment by VedVid** [comment]
Interesting... I build ASCII release from master by go get -u git.tuxfamily.org/boohu/boohu.git then go build. 

Now, the default mode is this one:  
![image](https://user-images.githubusercontent.com/16949680/49302784-5581b300-f4c8-11e8-9068-616351401437.png)  
but if I toggle FOV mode and quit game, then start it again, whole screen is, well, bright:  
![image](https://user-images.githubusercontent.com/16949680/49302898-8f52b980-f4c8-11e8-94f2-cb8b162d05c9.png)
In that case, toggling FOV once results in regular light mode, and next switch to the default one.

**Comment by VedVid** [comment]
Ups, it's even more complicated. Let me post gif here:  
![2018-11-30 17h55_36](https://user-images.githubusercontent.com/16949680/49303192-60891300-f4c9-11e8-8df0-56447d9c7a3f.gif)

**Comment by anaseto** [comment]
Oh, yes, hm, I've found the main culprit: I changed the way dark/light worked (now there is indeed a dark with green LOS, and a bright one), but the toggling for the windows 8-colour version only got half updated. I'll fix this asap.

**Comment by anaseto** [comment]
Hopefully now fixed with the last commit. Now there should be for the 8-colour palette a dark or light background, with green light in both cases.

Thanks for pointing out this issue!

**Comment by VedVid** [comment]
No problem, it's in my best interests as well ;)

Unfortunately, it still looks strange. I can switch between  
![image](https://user-images.githubusercontent.com/16949680/49304986-2ec67b00-f4ce-11e8-965d-1552cbd8d244.png)  
and  
![image](https://user-images.githubusercontent.com/16949680/49304997-38e87980-f4ce-11e8-80b3-652ede57d044.png)

This light blue is nice hue, but I don't think it's intended...

**Comment by anaseto** [comment]
Oops! Should be fixed now. The thing is, on my current OpenBSD machine I have to use the tcell backend and cannot even test myself the termbox backend I use for Windows, Linux and OS X binaries, portability is hard :-)

**Comment by VedVid** [comment]
In that case, it's good that I'm on Windows and have plenty of time. And Go environment set up already :)  

Now dark FOV looks as it's supposed to look, but the light one is still problematic - whole screen has bright background, only foreground changes. And tiles in player's FOV are still green.  
![image](https://user-images.githubusercontent.com/16949680/49305755-6cc49e80-f4d0-11e8-9f5d-dd6772a2b924.png)

**Comment by anaseto** [comment]
The light one did work in fact as I intented after the theme change I did after people pointed out to me that the contrast between LOS background and the rest was too much, and the results looks ok with 16 colors.

But the everything bright one is indeed not very pretty with 8 colours, so I switch it back again to how it worked before for the 8-color version! :-)

**Comment by VedVid** [comment]
Thanks! :) I think we can close this issue now.

**Comment by anaseto** [comment]
Great! And thanks again for helping debugging this :)

**Comment by VedVid** [comment]
I'm glad I was able to help :)
