### ISSUE TITLE
Add version or commit using -v

### ISSUE THREAD

**Issue by erf** [anaseto/boohu#3]
Add version ( if release version ) or commit using `-v`

**Comment by anaseto** [comment]
I've [added a variable](https://github.com/anaseto/boohu/commit/20517bb4f7aed08812b4db867ce9a176dd27b2f6) so that if you build using these flags  `go get -u -ldflags "-X main.Version=$(git describe --tags)" github.com/anaseto/boohu`, you get a complete version number using `-v`. Without flags I'll put just the last release version.

**Comment by anaseto** [comment]
Now that I think about it, perhaps I should add version to character dump too. 

Thanks for ponting this stuff out!

**Comment by erf** [comment]
Thanks! The reason i thought of this was because i wanted to see if i was on the latest version. Now it shows `v0.3` after i do a `go get -u github.com/anaseto/boohu` so I'm obviously on the latest version but if the commit version also was there ( if possible ), i could check against the git repo if i'm all up to date. Btw. Great game!

**Comment by anaseto** [comment]
Actually I wasn't very clear in my previous comment, but if you want the commit version along with the last version (and not only the version), you can do that by using `-ldflags` this way:

    cd $GOPATH/src/github.com/anaseto/boohu
    go get -u -ldflags "-X main.Version=$(git describe --tags)" github.com/anaseto/boohu

This will change at build time the value of the variable Version using `git describe --tags` and giving something like `v0.3-36-g20517bb` (so 36 commits after v0.3). You could put these two commands in a script. Perhaps I could write a Makefile with this.

Hope this helps, and I'm glad you like the game!

**Comment by erf** [comment]
I actually tried that but it `boohu -v` still outputs `v0.3`. I'm not familiar with go-lang, so maybe i'm doing something silly.

**Comment by anaseto** [comment]
Oh, probably the `go get -u` command did nothing because you already had the latest version. If that's the case, just remove the binary in `$GOPATH/bin/boohu` and try again (doing a touch on a file instead of removing the binary will do it too, I think).

**Comment by erf** [comment]
Thanks, that works!
