### ISSUE TITLE
Suggestions: 'G>' to go down nearest stairs

### ISSUE THREAD

**Issue by erf** [anaseto/boohu#4]
Suggestions: 'G>' to go down nearest stairs.

Like in DCSS.

**Comment by anaseto** [comment]
I'm not sure I understand, perhaps I'm missing something. In Boohu you can do `x>.` to chose a stair, like in DCSS, except that sometimes you have to cycle through several stairs, because I don't chose the nearest, so I should improve this : is this what you're refering to?

**Comment by erf** [comment]
Sorry. I meant `G>` - which walks to the nearest stairs, i've updated the comment. I did not know about `x>.` but that is even better, so maybe we don't need `G>`. Up to you :)

**Comment by anaseto** [comment]
Oh, `G>`, why not, I'll add this. I actually never use G to travel just to stairs in DCSS, don't know why, I only think about G for long distances :)

**Comment by erf** [comment]
Awesome 👍  I guess there are so many shortcuts, you get used to a subset and just stick to it 😄

**Comment by anaseto** [comment]
I added the G key-binding to go to nearest stairs (in the sense of shortest path), and now `x>` allows to cycle from nearest to farthest stair.

**Comment by erf** [comment]
Great!
