### ISSUE TITLE
Suggestion: Highlight beginning of latest console log.

### ISSUE THREAD

**Issue by erf** [anaseto/boohu#5]
Suggestion: 
Highlight beginning of latest console log. 
E.g. mark the first action of a 'tick' yellow, so it's easier to understand what is going on.

Tip:
Check out https://cryochamber.bandcamp.com/album/illuminatio for some really cool dungeon music :D

**Comment by anaseto** [comment]
Yeah, adding some colors to console log would be a good idea.

> Check out https://cryochamber.bandcamp.com/album/illuminatio for some really cool dungeon music :D

Quite dark indeed :)

**Comment by erf** [comment]
Maybe adding red color to the log if you get hit, or green if you do damage.

**Comment by anaseto** [comment]
I've added some preliminary colors to the console log, it needs perhaps still some tweaks. Thanks for the suggestion!

**Comment by erf** [comment]
Great work! It's now easier to see what happened in the previous tick.
