### ISSUE TITLE
Notify player when he gained level / aptitude

### ISSUE THREAD

**Issue by erf** [anaseto/boohu#9]
Suggestion:
Notify player when he gained a level / aptitude. E.g. "*New aptitude gained*"

I've only accidentally noticed this now when i have checked the character information.

Also show XP towards next level? Not sure if this is a good idea since i love the simplicity of the game now.

**Comment by erf** [comment]
Sorry. I see now that you actually do that. Haha

**Comment by anaseto** [comment]
Yeah, without colors it was not very obvious before :)

And there's not exactly XP in the game: you're just (almost) guaranteed to get in total three random aptitudes per game around some particular Depths (there are some random deviations for more replayability).
